name: Deploy PR Preview to GitHub Pages

env:
  WC_HUGO_VERSION: '0.124.1'

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.WC_HUGO_VERSION }}
          extended: true

      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build Site
        env:
          HUGO_ENVIRONMENT: production
        run: |
          hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/pr-preview/${{ github.event.number }}/"

      - name: Upload PR preview artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy PR Preview to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          destination_dir: pr-preview/${{ github.event.number }}

      - name: Add PR Comment with Preview Link
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-preview-link
          message: |
            :rocket: **Preview for this PR is available at:**
            https://axza.github.io/axell_de-hugoblox/pr-preview/${{ github.event.number }}/
